spring:
  application:
    name: discodeit

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

discodeit:
  repository:
    type: jcf
    file-directory: .discodeit
    discodeit:
      storage:
        type: local
        local:
          root-path: ./uploads

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace